ccfa:
  code: ccfa
  title: CCFA Partners
  condition: "Crohn's & Colitis"
  conditions:
    - Crohns
    - Ulcerative Colitis
    - Indeterminate Colitis
  research_questions:
    - Which is a more effective dosing schedule of Humira?
    - "Can a six week schedule of 10,000 steps improve Crohn's symptoms?"
    - Does sleeping on your side change the effects?
    - Does acupuncture work for Ulcerative Colitis?
    - Does Drug A work better than Drug B?
  research_team:
    -
      - Mike Kappelman
      - Researcher, GI
      - kappelman.jpg
  patient_team:
    -
      - Jessica Burris
      - "Crohn's Patient"
  surveys:
    - Basic Health Survey
    - Have you ever done SCD?
  data_sources:
    "GI Buddy":
      - :GI_symptoms
    "Fitbit":
      - :steps
      - :walking
      - :running
      - :sleep
      - :weight
    "Moves":
      - :steps
      - :walking
      - :running
      - :cycling
    "Nike+ Fuelband":
      - :steps
      - :running
    "MapMyFitness":
      - :walking
      - :running
      - :cycling
    "Crohnology":
      - :GI_symptoms
    "JawBone Up":
      - :steps
    "Body Media":
      - :steps
      - :running
      - :sleep
      - :heart_rate
      - :weight
    "RunKeeper":
      - :walking
      - :running
    "FitBit Aria":
      - :weight
      - :body_fat
    "Withings":
      - :steps
      - :walking
      - :running
      - :heart_rate
      - :weight
      - :body_fat
  data_source_types:
    - :steps
    - :walking
    - :running
    - :cycling
    - :sleep
    - :heart_rate
    - :weight
    - :body_fat
    - :GI_symptoms





myapnea:
  code: myapnea
  title: My Apnea
  condition: Sleep Apnea
  conditions:
    - Sleep Apnea
  research_questions:
    - Does doing exercise immediately before sleep work?
    - Does paprika immediately before bed work?
    - How has nasal surgery affected patients with Sleep Apnea?
    - Does Oxygen work better than drugs for subtype A of Sleep Apnea?
    - Does Drug A work better than Drug B?
  research_team:
    -
      - Susan Redline
      - "Researcher"
      -
  patient_team:
    -
      - Will Headaphol
      - Sleep Apnea Patient
      -
    -
      - Adam Admur
      - Sleep Apnea Patient
      -
  surveys:
    - Basic Health Survey
    - What treatments have you tried for your Apnea?
  data_sources:
    "Fitbit":
      - :steps
      - :walking
      - :running
      - :sleep
      - :weight
    "Moves":
      - :steps
      - :walking
      - :running
      - :cycling
    "Nike+ Fuelband":
      - :steps
      - :running
    "MapMyFitness":
      - :walking
      - :running
      - :cycling
    "JawBone Up":
      - :steps
    "Body Media":
      - :steps
      - :running
      - :sleep
      - :heart_rate
      - :weight
    "RunKeeper":
      - :walking
      - :running
    "FitBit Aria":
      - :weight
      - :body_fat
    "Withings":
      - :steps
      - :walking
      - :running
      - :heart_rate
      - :weight
      - :body_fat
  data_source_types:
    - :steps
    - :walking
    - :running
    - :cycling
    - :sleep
    - :heart_rate
    - :weight
    - :body_fat
